# frozen_string_literal: true

module RailsMigrations2sql
  module Compilers
    class Oracle < Base
      def initialize(**options)
        super(target: :oracle, **options)
      end

      def quote_identifier(name)
        %Q{"#{name.to_s.upcase.gsub('"', '""')}"}
      end

      def boolean_literal(value)
        value ? "1" : "0"
      end

      protected

      def type_sql(type, options = {})
        case type.to_sym
        when :string then "VARCHAR2(#{options[:limit] || 255})"
        when :text then "CLOB"
        when :integer then "NUMBER(10)"
        when :bigint then "NUMBER(19)"
        when :float then "BINARY_DOUBLE"
        when :decimal, :numeric
          options[:precision] ? "NUMBER(#{options[:precision]}#{options[:scale].nil? ? '' : ",#{options[:scale]}"})" : "NUMBER"
        when :boolean then "NUMBER(1)"
        when :date then "DATE"
        when :datetime, :timestamp then options[:precision] ? "TIMESTAMP(#{options[:precision]})" : "TIMESTAMP"
        when :time then "TIMESTAMP"
        when :binary then "BLOB"
        when :json, :jsonb then "CLOB"
        when :uuid then "RAW(16)"
        when :inet then "VARCHAR2(45)"
        else super
        end
      end

      def auto_increment_clause(_type, options)
        options[:primary_key] ? "GENERATED BY DEFAULT AS IDENTITY" : nil
      end

      def compile_add_column(op)
        "ALTER TABLE #{quote_table(op.args[0])} ADD (#{column_definition(op.args[1], op.args[2], op.options)})"
      end

      def compile_change_column(op)
        table, column, type = op.args.first(3)
        "ALTER TABLE #{quote_table(table)} MODIFY (#{column_definition(column, type, op.options)})"
      end

      def compile_change_column_default(op)
        value = change_to_value(op.args[2])
        clause = value.nil? ? "DEFAULT NULL" : "DEFAULT #{literal(value)}"
        "ALTER TABLE #{quote_table(op.args[0])} MODIFY (#{quote_column(op.args[1])} #{clause})"
      end

      def compile_change_column_null(op)
        clause = op.args[2] ? "NULL" : "NOT NULL"
        "ALTER TABLE #{quote_table(op.args[0])} MODIFY (#{quote_column(op.args[1])} #{clause})"
      end

      def compile_remove_index(op)
        table, columns = op.args.first(2)
        name = op.options[:name] || Util.default_index_name(table, columns)
        "DROP INDEX #{quote_identifier(name)}"
      end

      def compile_add_index(op)
        return unsupported!(op.name, "Oracle compiler does not translate where: partial indexes; use execute with Oracle SQL") if op.options[:where]
        super
      end

      def compile_add_foreign_key(op)
        return unsupported!(op.name, "Oracle does not support ON UPDATE on foreign keys") if op.options[:on_update]
        super
      end

      def compile_change_table_comment(op)
        value = change_to_value(op.args[1])
        "COMMENT ON TABLE #{quote_table(op.args[0])} IS #{literal(value)}"
      end

      def compile_change_column_comment(op)
        value = change_to_value(op.args[2])
        "COMMENT ON COLUMN #{quote_table(op.args[0])}.#{quote_column(op.args[1])} IS #{literal(value)}"
      end
    end
  end
end
