# frozen_string_literal: true

module RailsMigrations2sql
  module Compilers
    class PostgreSQL < Base
      def initialize(**options)
        super(target: :postgresql, **options)
      end

      protected

      def type_sql(type, options = {})
        case type.to_sym
        when :binary then "bytea"
        when :jsonb then "jsonb"
        when :uuid then "uuid"
        when :integer then options[:limit].to_i >= 8 ? "bigint" : "integer"
        when :bigint then "bigint"
        else super
        end
      end

      def auto_increment_clause(type, options)
        return nil unless options[:primary_key]
        return nil if type.to_sym == :uuid

        "GENERATED BY DEFAULT AS IDENTITY"
      end

      def compile_change_column(op)
        table, column, type = op.args.first(3)
        statements = ["ALTER TABLE #{quote_table(table)} ALTER COLUMN #{quote_column(column)} TYPE #{type_sql(type, op.options)}"]
        statements << compile_change_column_default(Operation.new(name: :change_column_default, args: [table, column, op.options[:default]])) if op.options.key?(:default)
        statements << compile_change_column_null(Operation.new(name: :change_column_null, args: [table, column, op.options[:null]])) if op.options.key?(:null)
        statements
      end

      def compile_remove_index(op)
        table, columns = op.args.first(2)
        name = op.options[:name] || Util.default_index_name(table, columns)
        concurrently = op.options[:algorithm].to_s == "concurrently" ? " CONCURRENTLY" : ""
        "DROP INDEX#{concurrently} #{quote_identifier(name)}"
      end

      def compile_enable_extension(op)
        "CREATE EXTENSION#{op.options[:if_not_exists] == false ? '' : ' IF NOT EXISTS'} #{quote_identifier(op.args[0])}"
      end

      def compile_disable_extension(op)
        "DROP EXTENSION#{op.options[:if_exists] == false ? '' : ' IF EXISTS'} #{quote_identifier(op.args[0])}"
      end

      def compile_change_table_comment(op)
        value = change_to_value(op.args[1])
        "COMMENT ON TABLE #{quote_table(op.args[0])} IS #{literal(value)}"
      end

      def compile_change_column_comment(op)
        value = change_to_value(op.args[2])
        "COMMENT ON COLUMN #{quote_table(op.args[0])}.#{quote_column(op.args[1])} IS #{literal(value)}"
      end
    end
  end
end
