# frozen_string_literal: true

require "fileutils"

module RailsMigrations2sql
  class PackageWriter
    attr_reader :path

    def initialize(migration_file:, compiler:, configuration:, up_sql:)
      @migration_file = migration_file
      @compiler = compiler
      @configuration = configuration
      @up_sql = up_sql
      @formatter = SqlFormatter.new(compiler.target)
    end

    def write
      directory = File.join(output_root, @compiler.target.to_s)
      FileUtils.mkdir_p(directory)
      @path = File.join(directory, "#{@migration_file.stem}.sql")

      body = @formatter.join(@up_sql)
      File.write(@path, [header("UP"), body, register_sql].reject(&:empty?).join("\n\n") + "\n")
      @path
    end

    private

    def output_root
      configured = @configuration.output_path
      return configured.to_s if configured

      root = defined?(Rails) && Rails.respond_to?(:root) && Rails.root ? Rails.root.to_s : Dir.pwd
      File.join(root, "db", "sql")
    end

    def header(direction)
      <<~TEXT.strip
        -- Generated by rails_migrations2sql #{RailsMigrations2sql::VERSION}
        -- Offline compilation: no migration was executed against a database
        -- Target: #{@compiler.target}
        -- Migration: #{@migration_file.version} #{@migration_file.class_name}
        -- Direction: #{direction}
        -- Source: #{@migration_file.filename}
        -- Review with your DBA before production execution.
      TEXT
    end

    def register_sql
      table = @compiler.quote_table(@configuration.schema_migrations_table_name)
      column = @compiler.quote_column("version")
      statement = "INSERT INTO #{table} (#{column}) VALUES (#{@compiler.literal(@migration_file.version.to_s)})"
      "-- Register the migration version after successfully applying the statements above.\n#{@formatter.format(statement)}"
    end

  end
end
