# frozen_string_literal: true

require "fileutils"
require "yaml"
require "digest"
require "time"

module RailsMigrations2sql
  class PackageWriter
    attr_reader :path

    def initialize(migration_file:, compiler:, configuration:, evaluation:, up_sql:, down_sql:)
      @migration_file = migration_file
      @compiler = compiler
      @configuration = configuration
      @evaluation = evaluation
      @up_sql = up_sql
      @down_sql = down_sql
      @formatter = SqlFormatter.new(compiler.target)
    end

    def write
      @path = File.join(output_root, @compiler.target.to_s, @migration_file.stem)
      FileUtils.mkdir_p(@path)

      write_sql("up.sql", header("UP"), @up_sql)
      if @evaluation.rollback_available
        write_sql("down.sql", header("DOWN"), @down_sql)
      else
        File.write(File.join(@path, "down.sql"), "#{header('DOWN')}\n\n-- UNAVAILABLE: #{@evaluation.rollback_error}\n")
      end
      File.write(File.join(@path, "register.sql"), register_sql)
      File.write(File.join(@path, "unregister.sql"), unregister_sql)
      File.write(File.join(@path, "manifest.yml"), manifest.to_yaml)
      @path
    end

    private

    def output_root
      configured = @configuration.output_path
      return configured.to_s if configured

      root = defined?(Rails) && Rails.respond_to?(:root) && Rails.root ? Rails.root.to_s : Dir.pwd
      File.join(root, "db", "dba_migrations")
    end

    def write_sql(filename, header, statements)
      body = @formatter.join(statements)
      content = [header, body].reject(&:empty?).join("\n\n")
      content << "\n" unless content.end_with?("\n")
      File.write(File.join(@path, filename), content)
    end

    def header(direction)
      <<~TEXT.strip
        -- Generated by rails_migrations2sql #{RailsMigrations2sql::VERSION}
        -- Offline compilation: no migration was executed against a database
        -- Target: #{@compiler.target}
        -- Migration: #{@migration_file.version} #{@migration_file.class_name}
        -- Direction: #{direction}
        -- Source: #{@migration_file.filename}
        -- Review with your DBA before production execution.
      TEXT
    end

    def register_sql
      table = @compiler.quote_table(@configuration.schema_migrations_table_name)
      column = @compiler.quote_column("version")
      statement = "INSERT INTO #{table} (#{column}) VALUES (#{@compiler.literal(@migration_file.version.to_s)})"
      "#{header('REGISTER')}\n\n#{@formatter.format(statement)}\n"
    end

    def unregister_sql
      table = @compiler.quote_table(@configuration.schema_migrations_table_name)
      column = @compiler.quote_column("version")
      statement = "DELETE FROM #{table} WHERE #{column} = #{@compiler.literal(@migration_file.version.to_s)}"
      "#{header('UNREGISTER')}\n\n#{@formatter.format(statement)}\n"
    end

    def manifest
      {
        "generator" => "rails_migrations2sql",
        "generator_version" => RailsMigrations2sql::VERSION,
        "offline" => true,
        "target" => @compiler.target.to_s,
        "migration" => @migration_file.to_h,
        "source_sha256" => Digest::SHA256.file(@migration_file.path).hexdigest,
        "active_record_version" => defined?(ActiveRecord::VERSION::STRING) ? ActiveRecord::VERSION::STRING : nil,
        "rails_version" => defined?(Rails) && Rails.respond_to?(:version) ? Rails.version : nil,
        "generated_at" => Time.now.utc.iso8601,
        "rollback_available" => @evaluation.rollback_available,
        "rollback_error" => @evaluation.rollback_error,
        "warnings" => @compiler.warnings,
        "up_operations" => serializable(@evaluation.up_operations.map(&:to_h)),
        "down_operations" => serializable(@evaluation.down_operations.map(&:to_h))
      }
    end

    def serializable(value)
      case value
      when Hash
        value.each_with_object({}) { |(key, item), memo| memo[key.to_s] = serializable(item) }
      when Array
        value.map { |item| serializable(item) }
      when Symbol
        value.to_s
      when Proc
        { "ruby_callable" => value.source_location&.join(":") || value.inspect }
      when String, Numeric, TrueClass, FalseClass, NilClass
        value
      else
        value.respond_to?(:to_s) ? value.to_s : value.inspect
      end
    end
  end
end
