# frozen_string_literal: true

module RailsMigrations2sql
  # Explicit offline export for seeds whose Ruby control flow requires data.
  # SQL collected here is executed only later by the DBA.
  class SeedScript
    Expression = Struct.new(:text)

    def self.selection(value)
      case value
      when nil, "", "auto" then :auto
      when "1" then true
      when "0" then false
      else raise ConfigurationError, "SEEDS must be 0, 1 or auto"
      end
    end

    def initialize(compiler:, configuration:)
      @compiler = compiler
      @configuration = configuration
      @statements = []
    end

    def prepare(path)
      @statements.clear
      path = File.expand_path(path)
      OfflineGuard.protect { instance_eval(File.read(path), path, 1) }
      root = @configuration.output_path || File.join(
        defined?(Rails) && Rails.respond_to?(:root) && Rails.root ? Rails.root.to_s : Dir.pwd,
        "db", "sql"
      )
      header = [
        "-- Generated by rails_migrations2sql #{RailsMigrations2sql::VERSION}",
        "-- Offline seed export; no SQL was executed against a database",
        "-- Source: #{File.basename(path)}",
        "-- Target: #{target}",
        "-- Review with your DBA before execution."
      ].join("\n")
      OutputFile.new(
        path: File.join(root.to_s, target.to_s, "seed.sql"),
        content: "#{header}\n\n#{SqlFormatter.new(target).join(@statements)}\n"
      )
    rescue StandardError, SyntaxError, LoadError => e
      location = e.backtrace&.find { |line| line.start_with?("#{path}:") }
      raise OfflineCompilationError, "Offline SQL seed compilation failed at #{location || path}: #{e.class}: #{e.message}"
    end

    def target = @compiler.target
    def quote(value) = value.is_a?(Expression) ? value.text : @compiler.literal(value)
    def quote_table(name) = @compiler.quote_table(name)
    def quote_column(name) = @compiler.quote_column(name)
    def sql(text) = Expression.new(text.to_s.dup.freeze).freeze

    def execute(statement)
      @statements << statement.to_s.dup.freeze
    end

    def insert(table, attributes, unless_exists: nil)
      validate_attributes!(attributes)
      columns = attributes.keys.map { |name| quote_column(name) }.join(", ")
      values = attributes.values.map { |value| quote(value) }.join(", ")
      statement = "INSERT INTO #{quote_table(table)} (#{columns})"
      if unless_exists
        predicate = conditions(unless_exists)
        from = target == :oracle ? " FROM DUAL" : ""
        statement += " SELECT #{values}#{from} WHERE NOT EXISTS (SELECT 1 FROM #{quote_table(table)} WHERE #{predicate})"
      else
        statement += " VALUES (#{values})"
      end
      execute(statement)
    end

    def update(table, attributes, where:)
      validate_attributes!(attributes)
      assignments = attributes.map { |name, value| "#{quote_column(name)} = #{quote(value)}" }.join(", ")
      execute("UPDATE #{quote_table(table)} SET #{assignments} WHERE #{conditions(where)}")
    end

    private

    def conditions(values)
      return values.text if values.is_a?(Expression)
      validate_attributes!(values)
      values.map do |name, value|
        column = quote_column(name)
        value.nil? ? "#{column} IS NULL" : "#{column} = #{quote(value)}"
      end.join(" AND ")
    end

    def validate_attributes!(attributes)
      unless attributes.is_a?(Hash) && !attributes.empty? &&
             attributes.keys.all? { |name| name.is_a?(String) || name.is_a?(Symbol) }
        raise ConfigurationError, "Seed attributes and conditions require a nonempty Hash with column names"
      end
      attributes.each_value do |value|
        supported = value.nil? || value == true || value == false ||
                    value.is_a?(String) || value.is_a?(Symbol) || value.is_a?(Numeric) ||
                    value.is_a?(Date) || value.is_a?(Time) ||
                    value.is_a?(ActiveSupport::TimeWithZone) || value.is_a?(Expression)
        raise UnsupportedOperationError, "Seed values must be scalar values or explicit sql(...) expressions" unless supported
      end
    end
  end
end
