# frozen_string_literal: true

require "date"
require "fileutils"

module RailsMigrations2sql
  class SeedRecorder
    CONTEXT_KEY = :rails_migrations2sql_seed_recorder

    class SeedRow
      attr_reader :attributes

      def initialize(attributes)
        @attributes = attributes.transform_keys(&:to_s)
      end

      def method_missing(name, *args)
        key = name.to_s
        if key.end_with?("=") && args.length == 1
          @attributes[key.delete_suffix("=")] = args.first
        elsif args.empty? && @attributes.key?(key)
          @attributes.fetch(key)
        else
          raise UnsupportedOperationError,
                "Seed record #{name} is unavailable offline; supply explicit values instead of relying on database-generated data"
        end
      end

      def respond_to_missing?(name, include_private = false)
        name.to_s.end_with?("=") || @attributes.key?(name.to_s) || super
      end
    end

    module ActiveRecordWrites
      def create(*records, **attributes, &block)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record(self, records, attributes, block)
      end

      def create!(*records, **attributes, &block)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record(self, records, attributes, block)
      end

      def find_or_create_by(*conditions, **attributes, &block)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record_find(self, conditions, attributes, block)
      end

      def find_or_create_by!(*conditions, **attributes, &block)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record_find(self, conditions, attributes, block)
      end

      def insert_all(rows, **options)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record_bulk(self, rows, options)
      end

      def insert_all!(rows, **options)
        recorder = Thread.current[SeedRecorder::CONTEXT_KEY]
        return super unless recorder

        recorder.record_bulk(self, rows, options)
      end
    end

    ActiveRecord::Base.singleton_class.prepend(ActiveRecordWrites)

    def self.capture(path)
      recorder = new
      previous = Thread.current[CONTEXT_KEY]
      Thread.current[CONTEXT_KEY] = recorder
      load path
      recorder.rows
    ensure
      Thread.current[CONTEXT_KEY] = previous
    end

    def self.write(rows, compiler:, configuration:)
      root = configuration.output_path || File.join(
        defined?(Rails) && Rails.respond_to?(:root) && Rails.root ? Rails.root.to_s : Dir.pwd,
        "db", "sql"
      )
      directory = File.join(root.to_s, compiler.target.to_s)
      FileUtils.mkdir_p(directory)
      path = File.join(directory, "seeds.sql")
      formatter = SqlFormatter.new(compiler.target)
      statements = rows.map do |entry|
        table = compiler.quote_table(entry[:table])
        attributes = entry[:attributes]
        columns = attributes.keys.map { |name| compiler.quote_column(name) }.join(", ")
        values = attributes.values.map { |value| compiler.literal(value) }.join(", ")
        if entry[:lookup]
          predicates = entry[:lookup].map do |name, value|
            column = compiler.quote_column(name)
            value.nil? ? "#{column} IS NULL" : "#{column} = #{compiler.literal(value)}"
          end.join(" AND ")
          from = compiler.target == :oracle ? " FROM DUAL" : ""
          "INSERT INTO #{table} (#{columns}) SELECT #{values}#{from} WHERE NOT EXISTS (SELECT 1 FROM #{table} WHERE #{predicates})"
        else
          "INSERT INTO #{table} (#{columns}) VALUES (#{values})"
        end
      end
      header = [
        "-- Generated by rails_migrations2sql #{RailsMigrations2sql::VERSION}",
        "-- Offline compilation of seed data; no seed was written to a database",
        "-- Target: #{compiler.target}",
        "-- Review with your DBA before production execution."
      ].join("\n")
      File.write(path, [header, formatter.join(statements)].reject(&:empty?).join("\n\n") + "\n")
      path
    end

    attr_reader :rows

    def initialize
      @rows = []
    end

    def record(model, positional, keywords, block)
      raise UnsupportedOperationError, "create/create! accepts one Hash or Array offline" if positional.length > 1 || (positional.any? && keywords.any?)

      data = positional.first || keywords
      if data.is_a?(Array)
        data.map { |attributes| add_row(model, attributes, block: block) }
      else
        add_row(model, data, block: block)
      end
    end

    def record_find(model, positional, keywords, block)
      raise UnsupportedOperationError, "find_or_create_by accepts one Hash offline" if positional.length > 1 || (positional.any? && keywords.any?)

      conditions = positional.first || keywords
      validate_attributes!(conditions)
      add_row(model, conditions, block: block, lookup: conditions.transform_keys(&:to_s))
    end

    def record_bulk(model, entries, options)
      raise UnsupportedOperationError, "insert_all options cannot be compiled offline" unless options.empty?
      raise UnsupportedOperationError, "insert_all expects an Array of Hashes" unless entries.is_a?(Array)

      entries.map { |attributes| add_row(model, attributes) }
    end

    private

    def add_row(model, attributes, block: nil, lookup: nil)
      validate_attributes!(attributes)
      row = SeedRow.new(attributes)
      block.call(row) if block
      validate_attributes!(row.attributes)
      @rows << { table: model.table_name, attributes: row.attributes.dup, lookup: lookup }
      row
    end

    def validate_attributes!(attributes)
      unless attributes.is_a?(Hash) && !attributes.empty?
        raise UnsupportedOperationError, "Seed inserts require a nonempty Hash of attributes"
      end

      attributes.each do |name, value|
        unless name.is_a?(String) || name.is_a?(Symbol)
          raise UnsupportedOperationError, "Seed column names must be strings or symbols"
        end
        supported = value.nil? || value == true || value == false ||
                    value.is_a?(String) || value.is_a?(Symbol) || value.is_a?(Numeric) ||
                    value.is_a?(Date) || value.is_a?(Time) || value.is_a?(ActiveSupport::TimeWithZone)
        raise UnsupportedOperationError, "Seed value for #{name} cannot be compiled offline" unless supported
      end
    end
  end
end
